name: minecraft-broadcaster
services:
  minecraft-broadcaster:
    build:
      context: .
      dockerfile: Dockerfile
    image: minecraft-broadcaster:latest
    container_name: minecraft-broadcaster
    restart: unless-stopped
    network_mode: host
    environment:
      - CRAFTY_API_URL=https://localhost:8443/api/v2
      - CRAFTY_USERNAME=${CRAFTY_USERNAME:-}
      - CRAFTY_PASSWORD=${CRAFTY_PASSWORD:-}
      - BROADCAST_IP=255.255.255.255
      - MINECRAFT_BROADCAST_PORT=4445
      - CHECK_INTERVAL=30
      - ENABLE_WEB_SERVER=true
      - WEB_SERVER_HOST=0.0.0.0
      - WEB_SERVER_PORT=8080
      - TEMPLATES_DIR=/app/templates
    ports:
      - "${WEB_SERVER_PORT:-8080}:8080"
    volumes:
      - ./templates:/app/templates
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"